### PR TITLE
Solr provider address

### PR DESCRIPTION
**Pull request by oajimenez**
Validated stored procedure for SOLRProviderAddress. 

Details to consider in the future: 
1. There is 0 delta data in SQL Server for this table dependency so this should be validated in the future when that data exists. 
2. Show.SOLRProviderAddress table definition has been altered in Snowflake to generate SOLRPROVIDERADDRESSID column. It's a numeric column but it does not gather the ID from any source (i.e., in the definition it looks something like this _SOLRPROVIDERADDRESSID NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 ORDER_)
3. Minor precision details in longitude/latitude from Mid tables. ADDRESSGEOPOINT column format due to minor differences in hexadecimal representation of SQL Server and Snowflake.

### CODE REVIEW

**Comment by oajimenez** [comment]
PR will be updated don't merge yet

**Review by omargoldpr — APPROVED** [review]
LGTM
5rN

**Review by omargoldpr — APPROVED** [review]
lgtm
5rN

**Review by ggandia-xtillion — APPROVED** [review]
lgtm
5rN

**Pull request merged**
