### PR TITLE
Base.ClientToProduct

### PR DESCRIPTION
**Pull request by oajimenez**
Used client swim lane view for this one too (very similar to other client tables). Only missing column is ReltioID but if I remember correctly that one was deprecated.

### CODE REVIEW

**Comment by oajimenez** [comment]
I may revise this soon, do not approve/merge yet

**Comment by oajimenez** [comment]
Update: Ready for review

**Review by carresemata — CHANGES_REQUESTED** [review]
1. Please change the table dependencies: Base.ClientToProduct instead of the comma
2. There is a clienttoproductid in this table that is never created here, please add it with uuid_string() in the insert

**Comment by oajimenez** [comment]
1. Done
2. I think the insertion is already there in line 78, unless you're referring to something else.

**Review by carresemata — APPROVED** [review]
Great!
Yes, I see the insertion now

**Pull request merged**
