### PR TITLE
Base.ProviderLastUpdateDate

### PR DESCRIPTION
**Pull request by oajimenez**
This thing generates an XML that records when updates are made to provider info. Validated by truncating the entire table and for a complex XML (ProviderID = '36545155-4b57-0000-0000-000000000000') ensuring the generated one is the same as SQL Server.

Also, le di cariñito a la función de XMLs pero it currently does not support nesting: DEV.JSON_TO_XML_2(VARCHAR, VARCHAR, VARCHAR). Si me inspiro luego voy a intentar hacerla recursiva pero I think Snowflake UDFs do not support recursion so habría que hacer un stored procedure para esto. 

**SQL Server**

```
<LastUpdateDateBySwimlane>
	<Demographics>
		<SourceCode>
			NPI
		</SourceCode>
		<LastUpdateDate>
			2023-04-29T13:46:53.517
		</LastUpdateDate>
	</Demographics>
	<License>
		<SourceCode>
			NPI
		</SourceCode>
		<LastUpdateDate>
			2023-12-19T08:26:33.620
		</LastUpdateDate>
	</License>
	<ProviderType>
		<SourceCode>
			Profisee
		</SourceCode>
		<LastUpdateDate>
			2024-04-20T21:29:32.953
		</LastUpdateDate>
	</ProviderType>
	<Status>
		<SourceCode>
			HGCALCULATED
		</SourceCode>
		<LastUpdateDate>
			2023-04-29T16:18:44.663
		</LastUpdateDate>
	</Status>
	<Degree>
		<SourceCode>
			NPI
		</SourceCode>
		<LastUpdateDate>
			2023-04-29T06:45:49.893
		</LastUpdateDate>
	</Degree>
	<HealthInsurance>
		<SourceCode>
			STRENUUS
		</SourceCode>
		<LastUpdateDate>
			2023-10-13T23:38:40.723
		</LastUpdateDate>
	</HealthInsurance>
	<ProviderSubType>
		<SourceCode>
			HGCALCULATED
		</SourceCode>
		<LastUpdateDate>
			2023-04-29T15:26:44.440
		</LastUpdateDate>
	</ProviderSubType>
</LastUpdateDateBySwimlane>
```

**Snowflake**
```
<LastUpdateDateBySwimlane>
    <Demographics>
        <SourceCode>NPI</SourceCode>
        <LastUpdateDate>1785443475-11-16 12:00:00.000</LastUpdateDate>
    </Demographics>
    <License>
        <SourceCode>NPI</SourceCode>
        <LastUpdateDate>-1869462635-03-21 23:13:20.000</LastUpdateDate>
    </License>
    <ProviderType>
        <SourceCode>Profisee</SourceCode>
        <LastUpdateDate>-1660212237-09-04 09:00:00.000</LastUpdateDate>
    </ProviderType>
    <Status>
        <SourceCode>HGCALCULATED</SourceCode>
        <LastUpdateDate>2023-04-29 16:18:44.663</LastUpdateDate>
    </Status>
    <Degree>
        <SourceCode>NPI</SourceCode>
        <LastUpdateDate>1784642903-07-01 23:40:00.000</LastUpdateDate>
    </Degree>
    <HealthInsurance>
        <SourceCode>STRENUUS</SourceCode>
        <LastUpdateDate>-2051168172-08-09 22:46:40.000</LastUpdateDate>
    </HealthInsurance>
    <ProviderSubType>
        <SourceCode>HGCALCULATED</SourceCode>
        <LastUpdateDate>2023-04-29 15:26:44.440</LastUpdateDate>
    </ProviderSubType>
</LastUpdateDateBySwimlane>
```

### CODE REVIEW

**Comment by oajimenez** [comment]
meme

**Review by carresemata — CHANGES_REQUESTED** [review]
This is amazing! Great job. A small note: you don't have any delete statement but you define it in the first section 1. You could remove it

**Comment by oajimenez** [comment]
Just remembered why that was there. In the original sp there was a join-delete that was executed before insertion. Did it with an update statement instead so it can be in the merge.

**Review by carresemata — APPROVED** [review]
Good to go!

**Pull request merged**
